In [1]:
import nltk
import string
import pandas as pd
import numpy as np
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /home/rucha/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [9]:
df=pd.read_csv("labeled_feedback_2.csv")

In [10]:
df.head(10)

,app_id,app_name,review_id,user_name,review_text,rating,thumbs_up,review_date,reply_text,reply_date,sentiment,category,priority,clean_text,review_length,word_count,has_reply,review_month,prediction_confidence
0,com.microsoft.teams,Microsoft Teams,e12ddbbd-07e4-4617-abc6-2548302c8aee,Rabih Suleiman,well good,5,0,2026-07-03 16:02:57,NaN,NaN,NaN,Complaint,NaN,NaN,9,2,0,2026-07,0.256937
1,com.microsoft.teams,Microsoft Teams,ed996656-98ac-4a5f-b568-aedf6c7fac12,Surender Lamba,Very helpful.,5,0,2026-07-03 15:44:18,NaN,NaN,NaN,Complaint,NaN,NaN,13,2,0,2026-07,0.256937
2,com.microsoft.teams,Microsoft Teams,7eaffbf3-2bbd-4c09-bb81-68d39f30f88d,Pardeep Ghalot,good app,4,0,2026-07-03 15:28:49,NaN,NaN,NaN,Complaint,NaN,NaN,8,2,0,2026-07,0.256937
3,com.microsoft.teams,Microsoft Teams,8666ccf4-0ff0-4fce-8291-a5fb862071ff,Debashis Das,I love it,5,0,2026-07-03 14:45:04,NaN,NaN,NaN,Complaint,NaN,NaN,9,3,0,2026-07,0.256937
4,com.microsoft.teams,Microsoft Teams,21166ae9-b5f9-402e-9d02-f7c2eda6c136,Dr. M.S. Nijamudeen,very good,5,0,2026-07-03 13:46:05,NaN,NaN,NaN,Complaint,NaN,NaN,9,2,0,2026-07,0.256937
5,com.microsoft.teams,Microsoft Teams,10f285dd-3b65-469f-b160-4f09cbe9a059,Rohit Mishra,nice,5,0,2026-07-03 13:44:22,NaN,NaN,NaN,Complaint,NaN,NaN,4,1,0,2026-07,0.256937
6,com.microsoft.teams,Microsoft Teams,7ad90209-6162-4343-bab4-c36ff9b1632a,Hakim Tahir,thanks for making your apps hard to navigate,1,0,2026-07-03 13:38:49,NaN,NaN,NaN,Complaint,NaN,NaN,44,8,0,2026-07,0.256937
7,com.microsoft.teams,Microsoft Teams,c5dfb751-d50e-4944-ad9e-4e5d09240fa0,Sourav Das,use full,5,0,2026-07-03 13:06:44,NaN,NaN,NaN,Complaint,NaN,NaN,8,2,0,2026-07,0.256937
8,com.microsoft.teams,Microsoft Teams,2a11874c-6a98-45a4-839f-529b8fa6ff85,Khan Javed,bad,1,0,2026-07-03 12:54:10,NaN,NaN,NaN,Complaint,NaN,NaN,3,1,0,2026-07,0.256937
9,com.microsoft.teams,Microsoft Teams,047e18d7-e72e-40b9-ad84-9c32be35d2a5,Ferris Maghi,when i open the app with no internet connectio...,1,0,2026-07-03 12:52:54,NaN,NaN,NaN,Complaint,NaN,NaN,196,40,0,2026-07,0.256937

In [11]:
df.shape

(56000, 19)

In [12]:
df["review_text"]

0                                                well good
1                                            Very helpful.
2                                                 good app
3                                                I love it
4                                                very good
                               ...
55995         nice app to easily use and simply understand
55996                                             good app
55997    good experience easy-to-use everything will be...
55998                                                   ok
55999                                              awesome
Name: review_text, Length: 56000, dtype: object

In [13]:
df.isnull().sum()

app_id                       0
app_name                     0
review_id                    0
user_name                    0
review_text                  0
rating                       0
thumbs_up                    0
review_date                  0
reply_text               43637
reply_date               43637
sentiment                56000
category                     0
priority                 56000
clean_text               56000
review_length                0
word_count                   0
has_reply                    0
review_month                 0
prediction_confidence        0
dtype: int64

In [14]:
df = df[df["review_text"].notna()]

df = df[df["review_text"].str.strip() != ""]

In [15]:
import re
stop_words = set(stopwords.words("english"))

def clean_text(text):

    text = str(text)

    # lowercase
    text = text.lower()

    # remove urls
    text = re.sub(r"http\S+", "", text)

    # remove special chars
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text)

    # remove stopwords
    words = text.split()

    words = [
        word for word in words
        if word not in stop_words
    ]

    return " ".join(words)
df["clean_text"]=df["review_text"].apply(clean_text)

In [16]:
df["clean_text"].isnull().sum()

np.int64(0)

In [17]:
df["review_length"] = (
    df["clean_text"]
    .str.len()
)

df["word_count"] = (
    df["clean_text"]
    .str.split()
    .str.len()
)

df["has_reply"] = (
    df["reply_text"]
    .notna()
    .astype(int)
)

df["source"] = "playstore"

In [18]:
df[
    [
        "review_text",
        "clean_text",
        "word_count"
    ]
].head(20)

,review_text,clean_text,word_count
0,well good,well good,2
1,Very helpful.,helpful,1
2,good app,good app,2
3,I love it,love,1
4,very good,good,1
5,nice,nice,1
6,thanks for making your apps hard to navigate,thanks making apps hard navigate,5
7,use full,use full,2
8,bad,bad,1
9,when i open the app with no internet connectio...,open app internet connection goes log loop fix...,18
10,"Works, use it because I have to, it's what it ...",works use another tool,4
11,good,good,1
12,good,good,1
13,ok,ok,1
14,deleted app: didn't use,deleted app use,3
15,great app,great app,2
16,I get hw but write to my friends but can't out...,get hw write friends country,5
17,it is very good and usefull,good usefull,2
18,"Please fix camera for itel VistaTab 30 Pro, th...",please fix camera itel vistatab pro picture ca...,12
19,good app fr,good app fr,3

In [19]:
df = df[
    df["clean_text"].str.strip() != ""
]

In [20]:
df[
    [
        "review_text",
        "clean_text",
        "word_count"
    ]
].head(20)

,review_text,clean_text,word_count
0,well good,well good,2
1,Very helpful.,helpful,1
2,good app,good app,2
3,I love it,love,1
4,very good,good,1
5,nice,nice,1
6,thanks for making your apps hard to navigate,thanks making apps hard navigate,5
7,use full,use full,2
8,bad,bad,1
9,when i open the app with no internet connectio...,open app internet connection goes log loop fix...,18
10,"Works, use it because I have to, it's what it ...",works use another tool,4
11,good,good,1
12,good,good,1
13,ok,ok,1
14,deleted app: didn't use,deleted app use,3
15,great app,great app,2
16,I get hw but write to my friends but can't out...,get hw write friends country,5
17,it is very good and usefull,good usefull,2
18,"Please fix camera for itel VistaTab 30 Pro, th...",please fix camera itel vistatab pro picture ca...,12
19,good app fr,good app fr,3

In [21]:
df[
    [
        "review_text",
        "clean_text",
        "word_count"
    ]
].head(20)

,review_text,clean_text,word_count
0,well good,well good,2
1,Very helpful.,helpful,1
2,good app,good app,2
3,I love it,love,1
4,very good,good,1
5,nice,nice,1
6,thanks for making your apps hard to navigate,thanks making apps hard navigate,5
7,use full,use full,2
8,bad,bad,1
9,when i open the app with no internet connectio...,open app internet connection goes log loop fix...,18
10,"Works, use it because I have to, it's what it ...",works use another tool,4
11,good,good,1
12,good,good,1
13,ok,ok,1
14,deleted app: didn't use,deleted app use,3
15,great app,great app,2
16,I get hw but write to my friends but can't out...,get hw write friends country,5
17,it is very good and usefull,good usefull,2
18,"Please fix camera for itel VistaTab 30 Pro, th...",please fix camera itel vistatab pro picture ca...,12
19,good app fr,good app fr,3

In [22]:
df.to_csv(
    "cleaned_feedback.csv",
    index=False
)

print("Preprocessing completed")

Preprocessing completed